# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencode < Formula
  desc ""
  homepage ""
  version "0.0.35"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opencode-ai/opencode/releases/download/v0.0.35/opencode-mac-x86_64.tar.gz"
      sha256 "68826f91bba87953aea4783a95ca1fbe5644e8e8292329cf7827b2b05e579106"

      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opencode-ai/opencode/releases/download/v0.0.35/opencode-mac-arm64.tar.gz"
      sha256 "d487fb3c14f48d99f974f7a1702148c618f987543f3b262cc97eb86aa7ddcf6e"

      def install
        bin.install "opencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opencode-ai/opencode/releases/download/v0.0.35/opencode-linux-x86_64.tar.gz"
        sha256 "8b30c7a5a3c0b0cd5bb0a6ab51379118077f48fb6289c82073f89428b1b8935c"

        def install
          bin.install "opencode"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opencode-ai/opencode/releases/download/v0.0.35/opencode-linux-arm64.tar.gz"
        sha256 "ba8ad4f7cea3454da7a939c66a2ed2df74f0950c996e1190a4436662f2d6c4c9"

        def install
          bin.install "opencode"
        end
      end
    end
  end
end
