# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencode < Formula
  desc ""
  homepage ""
  version "0.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opencode-ai/opencode/releases/download/v0.0.12/opencode-mac-x86_64.tar.gz"
      sha256 "6100178436409161c784d8d44b1c69f40453935314aed08df2a6f504a4f30827"

      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opencode-ai/opencode/releases/download/v0.0.12/opencode-mac-arm64.tar.gz"
      sha256 "f78d1219663292b4127b712b1c371e070210ba0629f286c57e7e5773cb802be9"

      def install
        bin.install "opencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opencode-ai/opencode/releases/download/v0.0.12/opencode-linux-x86_64.tar.gz"
        sha256 "895f491a37fe83fd1fc2bb05042df00af0f9f1b42f96571c9b621ec02fe22c03"

        def install
          bin.install "opencode"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/opencode-ai/opencode/releases/download/v0.0.12/opencode-linux-arm64.tar.gz"
        sha256 "85eec24fa56ee4cb23aae13ca12174147f47786007feb40fa7026aa148785efd"

        def install
          bin.install "opencode"
        end
      end
    end
  end
end
