# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencode < Formula
  desc ""
  homepage ""
  version "0.0.37"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opencode-ai/opencode/releases/download/v0.0.37/opencode-mac-x86_64.tar.gz"
      sha256 "515096cbe8f3f0cd1eb43c37e1709a1993db79ba1246ada530b6daef207cfb81"

      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/opencode-ai/opencode/releases/download/v0.0.37/opencode-mac-arm64.tar.gz"
      sha256 "d10057f7a9eb406ffaf9c5a0543867b7a7482c27c9ece30314e8b6eeae3e5af9"

      def install
        bin.install "opencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/opencode-ai/opencode/releases/download/v0.0.37/opencode-linux-x86_64.tar.gz"
      sha256 "28c8c487f15ab729135c3283db9632911baea9bfb3aaf9805a9767c11903bec4"
      def install
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/opencode-ai/opencode/releases/download/v0.0.37/opencode-linux-arm64.tar.gz"
      sha256 "b2923b2bfbfa797fa8072ff9e390f5796bc663d65bacade890eddb6b75cebfeb"
      def install
        bin.install "opencode"
      end
    end
  end
end
